name: Generate 3D Contribution Graph (Platane)

on:
  schedule:
    - cron: "0 3 * * *" # 每天凌晨自动运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate 3D contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: Chaniug
          outputs: |
            profile-3d/contrib.svg
      - name: Ensure profile-3d directory exists
        run: mkdir -p profile-3d
      - name: List generated files (debug)
        run: ls -l profile-3d
      - name: Commit and push 3D contribution graph
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'chore: update 3D contribution graph (Platane)'
          add: 'profile-3d/contrib.svg'
          push: true
