name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 2 * * *" # 每天凌晨自动运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Chaniug
      - name: Deploy to main branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'chore: update 3D contribution graph'
          add: 'profile-3d/contrib.svg'
          push: true
