name: Update Recent Activity

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}